const edFolha = [
    {
        titulo: "javaScript",
        preço: 15
    },
    {
        titulo: "php",
        preço: 25
    },
    {
        titulo: "java",
        preço: 24
    },
    {
        titulo: "GO",
        preço: 40
    },
    {
        titulo: "elixir",
        preço: 50
    }
];

const edGalho = [
    {
        titulo: "python",
        preço: 20
    },
    {
        titulo: "rust",
        preço: 22
    },
    {
        titulo: "ruby",
        preço: 28
    },
    {
        titulo: "c++",
        preço: 35
    },
    {
        titulo: "scala",
        preço: 44
    },
    {
        titulo: "pascal",
        preço: 0.50
    }
];

module.exports = { edFolha, edGalho };